name: deploy

on:
  push:
    branches:
      - add-branch-param-to-deploy-workflow
      - main
      - staging
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: Obligatorio-Devops
          owner: fmsoldo
          event_type: deploy
          message: |
            {
              "repository": "${{ github.repository }}",
              "service_name": "orders-service",
              "commit": "${{ github.sha }}",
              "branch": "${{ steps.branch-name.outputs.current_branch }}",
              "jar_file": "orders-service-example.jar"
            }
